# Generated by Django 4.2.6 on 2023-11-22 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_subject_course"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="offering_id",
            field=models.CharField(blank=True, max_length=36, null=True),
        ),
    ]
