# Generated by Django 4.2.6 on 2023-11-26 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_subject_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='total_seats',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='course',
            name='used_seats',
            field=models.IntegerField(default=0),
        ),
    ]
