# Generated by Django 4.2.6 on 2023-11-28 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0013_merge_0009_alter_course_sections_0012_section_number"),
    ]

    operations = [
       
      
    ]
