# Generated by Django 4.2.6 on 2023-11-28 22:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0014_remove_course_offering_id_remove_course_sections"),
    ]

    operations = [
      
    ]
