# Generated by Django 4.2.7 on 2023-12-03 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0021_alter_course_credit_option"),
    ]

    operations = [
        
    ]
