# Generated by Django 4.2.6 on 2023-11-26 23:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_course_total_seats_course_used_seats'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='total_seats',
        ),
        migrations.RemoveField(
            model_name='course',
            name='used_seats',
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timeslot', models.CharField(max_length=255)),
                ('professor', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('total_seats', models.IntegerField(default=0)),
                ('used_seats', models.IntegerField(default=0)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='users.course')),
            ],
        ),
    ]
