# Generated by Django 4.2.6 on 2023-11-22 21:01

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_course_sections"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="sections",
            field=jsonfield.fields.JSONField(blank=True, null=True),
        ),
    ]
