# Generated by Django 4.2.6 on 2023-11-27 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_section_section_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='section_id',
            field=models.IntegerField(default=0),
        ),
    ]
