# Generated by Django 4.2.6 on 2023-11-30 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0016_remove_course_offering_id_remove_course_sections_and_more"),
    ]

    operations = [
        
        migrations.RemoveField(
            model_name="coursewatch",
            name="user",
        ),
        migrations.AddField(
            model_name="customuser",
            name="course_watches",
            field=models.ManyToManyField(
                blank=True, related_name="students", to="users.coursewatch"
            ),
        ),
    ]
