# Generated by Django 4.2.6 on 2023-11-30 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0017_remove_course_offering_id_remove_course_sections_and_more"),
    ]

    operations = [
        
    ]
