# Generated by Django 4.2.6 on 2023-12-01 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_course_credit_option'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='credit_option',
            field=models.IntegerField(default=0),
        ),
    ]
