# Generated by Django 4.2.6 on 2023-12-02 19:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_coursewatch_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursewatch',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
