# Generated by Django 4.2.6 on 2023-12-02 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_coursewatch_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursewatch',
            name='user',
        ),
    ]
